#name: permissition_request_plugin
#description: "A new Flutter project."
version: 0.0.1
name: 'permisstion_request_plugin'
#homepage:

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.1
  package_info_plus: ^9.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  logger:

  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.2
  freezed: ^3.2.3
  build_runner: ^2.10.4
  analyzer:
#
flutter:
  plugin:
    platforms:
      android:
        package: com.vietec.app.plugin.permissition_request_plugin
        pluginClass: PermisstionRequestPlugin
      ios:
        pluginClass: PermisstionRequestPlugin
#      linux:
#        pluginClass: PermisstionRequestPlugin
#      macos:
#        pluginClass: PermisstionRequestPlugin
#      windows:
#        pluginClass: PermisstionRequestPluginCApi
#      web:
#        pluginClass: PermisstionRequestPluginWeb
#        fileName: permisstion_request_plugin_web.dart
